### ISSUE TITLE
Connecting to Grafana

### ISSUE THREAD

**Issue by Mikeguy74** [gstatton/cohesityGrafana#4]
I am having trouble understanding how to get this to work in Cohesity.

I can get though the part of getting the default DB Username and default DB password, but how do I do this step?

_Create a new data source in Grafana that is of type Postgres, the input the information from the output (from the link above)._

When I click on Open App in Cohesity it brings me to a login page but I do not know what credentials to use there to get in further.

Any help would be great!

Thank you,
Mike

**Comment by gstatton** [comment]
When you start up grafana is has the default admin/admin credentials and will prompt you to change them before fully logging in. 

I’m sorry I did not include that step in the instructions. Please let me know if you have any more issues!!

**Comment by Mikeguy74** [comment]
Thank you, I was able to get in and I was able to get the information and make the connection, or at least I believe I did.

Is the template the cohesityGrafana-main.zip?

Once that is downloaded, how do I import it?

Thank you,
Mike

**Comment by gstatton** [comment]
the demo template is located here: https://github.com/gstatton/cohesityGrafana/blob/main/Dashboard/custom_reporting_dashbaord.json It really is meant to get you started, but is by no means extensive. If there are stats/metrics you would like to see, please file an issue and i will try to get them into the template!

Thank you so much for trying this out!
